---
author: "Michael S. Taylor"
mainfont: Linux Libertine O
output:
  pdf_document:
    latex_engine: lualatex
    includes:
      in_header: advisee_header.tex
---

```{r setup, include=FALSE, echo=FALSE}
options(knitr.table.format = "latex")
```

```{r include=FALSE, echo=FALSE}
library(rvest)
library(dplyr)
#library(janitor)
library(stringr)
library(kableExtra)

semester <- "Fall 2024"
advisor <- "Michael S. Taylor"
file_name <- "roster_f2024"
#file_name <- scan("file_name.txt", what = "character")
html_dat <- read_html(paste0(file_name, ".html"))

roster <- html_dat %>% 
  html_elements(css = ".datadisplaytable") %>% 
  html_table() %>% 
  purrr::pluck(1) %>% 
  janitor::clean_names() %>% 
  filter(!grepl("Email", student_name)) %>% 
  filter(!is.na(id)) %>% 
  select(student_name, id, pin = alternate_pin)

email <- 
  html_dat %>% 
  html_elements(xpath = "//a[starts-with(@href,'mailto:')]") %>% 
  html_attr("href") %>% 
  last() %>% # takes last item from vector, so mailto email string
  str_remove("mailto:\\?Bcc=") %>% 
  str_split(pattern = ";") %>% 
  unlist()

roster <- 
  bind_cols(
    roster, 
    tibble(Email = email)
  ) %>% 
  mutate(row = row_number()) |> 
  select(row, `Student Name` = student_name, ID = id, Email, `Alternate PIN` = pin) %>% 
  mutate(`Alternate PIN` = str_replace_na(`Alternate PIN`, ""))

num_advisees <- dim(roster)[1]

```

\textsc{Taylor Advising Roster} \newline
`r paste0(semester, " (", num_advisees, " advisees)")`\newline

```{r echo=FALSE}
knitr::kable(roster, booktabs = TRUE, align = "rlllr", col.names = c("", "Student Name", "ID", "Email", "Alternate PIN"))
```

